spring:
  application:
    name: RedisService
  redis:
    uri: redis-cli -u redis://default:iTWzT8rgOuxvHBx3J5p4DVk4crq98IWC@redis-16525.c8.us-east-1-3.ec2.redns.redis-cloud.com:16525
  data:
    redis:
      host: redis-16525.c8.us-east-1-3.ec2.redns.redis-cloud.com
      port: 16525
      username: default
      password: iTWzT8rgOuxvHBx3J5p4DVk4crq98IWC
      ssl:
        enabled: true
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: 8081
  address: 0.0.0.0
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
