spring:
  application:
    name: FileService
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/fileDB?createDatabaseIfNotExist=true&serverTimezone=UTC&ssl-mode=REQUIRED
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  api_key: 532361965492273
  api_secret: XgJlA8F_LcyNwpiIXdnLEZnJsKo
  cloud_name: dclib4xzd

server:
  port: 8084
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
