spring:
  application:
    name: UserService
  datasource:
    url: "jdbc:mysql://localhost:3306/userDB?createDatabaseIfNotExist=true"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true