spring:
  application:
    name: AuthenService
  datasource:
    url: jdbc:mysql://mysql-169f260-minhdaimk112-2627.e.aivencloud.com:20605/authenDB?createDatabaseIfNotExist=true&serverTimezone=UTC&ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_G3GnbbZBxGNpakW4PMx
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8080
  address: 0.0.0.0
jwt:
  signedJWT: "aGUDzL2OOlvQcHJE5fpfzxv0w6MUZtFhF4IRZo+Tc/z5FnKjn8xxJvoot4OVj6LP"
  valid-duration: 3600
  refreshable-duration: 360000
